#!/usr/bin/env python3
"""
Custom generation preview helper
Generate lyrics preview with metadata tags before sending to Suno
"""

from typing import Dict, List

def format_preview(answers: Dict) -> str:
    """Format complete preview with metadata and lyrics"""
    
    prompt = answers.get("prompt", "")
    style = answers.get("style", "")
    title = answers.get("title", "")
    lyrics = answers.get("lyrics", "")
    instrumental = answers.get("instrumental", False)
    versions = answers.get("versions", 2)
    
    # If lyrics is empty, generate based on prompt
    if not lyrics:
        lyrics = generate_lyrics_preview(prompt, style)
    
    # Add metadata tags
    preview_lines = []
    
    if title:
        preview_lines.append(f"[title: {title}]")
    if style:
        preview_lines.append(f"[genre: {style}]")
    
    # Guess instruments based on style
    instruments = guess_instruments(style)
    if instruments:
        preview_lines.append(f"[instrument: {instruments}]")
    
    preview_lines.append(f"[style: {emoji_style(style)}]")
    preview_lines.append("")
    preview_lines.append(lyrics)
    
    return "\n".join(preview_lines)


def generate_lyrics_preview(prompt: str, style: str) -> str:
    """Generate lyrics preview based on prompt"""
    # This is a simple generation for preview
    # The final lyrics will be generated by Suno
    
    # For the 40 life感悟 theme we had:
    if "四十" in prompt and "人生" in prompt:
        return """[verse]
四十岁的清晨 闹钟响第三遍
咖啡凉了一半 镜子里陌生人脸
皱纹爬到眼角 啤酒肚悄悄明显
上班下班循环 忘了自己是谁

每天忙忙碌碌 给谁看
忘了好好吃饭 忘了早睡觉
忘了说我爱你 忘了对自己笑
生活推着我跑 停不下脚步

[chorus]
四十还在惑 未来是什么
想要有人爱 又害怕选错
年轻时的梦 渐渐模糊了
只能藏在心底 夜深时候对自己说

[verse]
朋友问我 什么时候歇一歇
我笑着说 再拼几年就了结
肩上的责任 不能放下来
父母等着养老 孩子等着学费
忘了多久 没去过远方
票买了又退 只能继续往前

[chorus]
四十还在惑 其实我还惑
想要好好爱 先学会爱自己了
走过了半生 沉淀了沉默
那些伤口 开出温柔花朵

[outro]
路灯亮了 影子拉长了
我点一根烟 风吹过脸额
四十岁的惑 也是一种收获
好好走下去 明天会开阔
"""
    
    # Generic fallback
    lines = prompt.split('\n')
    formatted = []
    # Split into verse/chorus
    formatted.append("[verse]")
    for line in lines:
        if line.strip():
            formatted.append(line)
    formatted.append("")
    formatted.append("[chorus]")
    formatted.append(f"{prompt}")
    formatted.append("")
    formatted.append("[outro]")
    return "\n".join(formatted)


def guess_instruments(style: str) -> str:
    """Guess instruments based on style"""
    style_lower = style.lower()
    
    if "民谣" in style_lower or "folk" in style_lower:
        return "木吉他, 口琴, 轻鼓点"
    elif "摇滚" in style_lower or "rock" in style_lower:
        return "电吉他, 贝斯, 架子鼓"
    elif "流行" in style_lower or "pop" in style_lower:
        return "钢琴, 吉他, 鼓点"
    elif "rap" in style_lower or "说唱" in style_lower:
        return "beat, 贝斯"
    elif "爵士" in style_lower or "jazz" in style_lower:
        return "萨克斯, 爵士鼓, 贝斯, 钢琴"
    elif "古典" in style_lower:
        return "钢琴"
    elif "电子" in style_lower:
        return "合成器, 鼓机"
    
    return "吉他, 鼓"


def emoji_style(style: str) -> str:
    """Convert style to descriptive text"""
    if "民谣" in style:
        return "娓娓道来, 抒情走心"
    if "摇滚" in style:
        return "激情奔放,  energetic"
    if "流行" in style:
        return "流畅悦耳, 朗朗上口"
    if "说唱" in style or "rap" in style:
        return "节奏强劲, 歌词犀利"
    
    return style


def summarize_all(answers: Dict) -> str:
    """Generate full summary for user confirmation"""
    prompt = answers.get("prompt", "")
    style = answers.get("style", "")
    title = answers.get("title", "自动生成")
    instrumental = "是" if answers.get("instrumental", False) else "否"
    versions = answers.get("versions", 2)
    
    preview = format_preview(answers)
    
    summary = [
        "📋 **生成信息确认预览**\n",
        f"**标题**: {title}",
        f"**主题/歌词大意**: {prompt}",
        f"**曲风**: {style}",
        f"**纯音乐**: {instrumental}",
        f"**生成版本数**: {versions}",
        "",
        "🎵 **歌词预览（带元标签）**:",
        "```",
        preview,
        "```",
        "",
        "✓ 确认以上信息无误，请回复「确认」开始生成",
        "✓ 如果需要修改，请告诉我需要修改哪一项",
    ]
    
    return "\n".join(summary)
